### ISSUE TITLE
Send CSRF Token

### ISSUE THREAD

**Issue by akdbra** [TylerGarlick/angular-redactor#10]
I wanted to add to request body my csrf token. Is there any option or callaback for that task?

**Comment by nmarcetic** [comment]
@TylerGarlick  thank you for this great module. 
Redactor 2 use vanila JS, not jQuery ajax calls , e.g  XMLHttpRequest so $.ajaxSetup will not work.
I still have a problem with "sending csrf token" on image upload, very annoying.
 I use https://github.com/krakenjs/lusca on  API side.
