### ISSUE TITLE
Hi, The library??

### ISSUE THREAD

**Issue by carlosCeron** [TylerGarlick/angular-redactor#30]
although the question it's obviously, The library Redactor, it's no free, we need pay this library to use  this directive ?? Thanks

**Comment by OKNoah** [comment]
But the library is not free, and by extension it costs money to actually use this. Right? I think that is the question.

**Comment by TylerGarlick** [comment]
That's correct. Redactor is not freeware.

**Comment by d00n** [comment]
..and worth the money, imho. These guys are getting it done:

http://imperavi.com/redactor/log/
