### ISSUE TITLE
Pass Clips Snippets

### ISSUE THREAD

**Issue by carlosCeron** [TylerGarlick/angular-redactor#32]
Hi, guys 

I try to pass snippets to clips module, but i don't know what it's the correct way, thanks Guys

$scope.redactorOptions.plugins = ['clips'];

**Comment by johntom** [comment]
See #33 as I got the clips to work.
HTH
John

**Comment by TylerGarlick** [comment]
@carlosCeron can I close?

**Comment by carlosCeron** [comment]
Yeah, this issue was solved.
