### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by gabehayes** [TylerGarlick/angular-redactor#43]
Would be nice to also support installing this package via npm.

If you would prefer to not actually publish, having a `package.json` file that points to the appropriate main script would suffice.

I would have gladly submitted a PR for the change, but I didn't want to generate the `package.json` file as there are fields such as author, license, etc that are probably more appropriate for you to handle.

**Comment by bartes** [comment]
+1

**Comment by turbobeast** [comment]
:+1:

**Comment by Till034** [comment]
:+1:

**Comment by consigliory** [comment]
+1
