### ISSUE TITLE
editing text isn't updating ng-model

### ISSUE THREAD

**Issue by allumbra** [TylerGarlick/angular-redactor#5]
Hello, I'm trying out your project for the first time tonight.  I can set the content of the redactor widget using $scope.content = "replace this content";   However, when editing the text in the control and logging it out, it isn't updating the model.

The html:

``` html
<textarea ng-model="content" redactor cols="45" rows="12"></textarea>
<button type="button"
     class="btn btn-mini  btn-success"
     ng-click="saveComment(event)">Save
</button>
```

js snippet:

``` javascript
$scope.content = "<b> replace this text </b>";

$scope.saveComment = function (event){
            console.log($scope.content);
}
```

Any tips? It all looks refreshingly simple, but it is 11:30 at night and I could be doing something bone headed.  Thanks

**Comment by josecastilho** [comment]
Friend, i´m with the same problem but i don´t undertood you solution. Could you post it here??  tks
