### ISSUE TITLE
Error: No such method "code.set" for Redactor

### ISSUE THREAD

**Issue by carradjm** [TylerGarlick/angular-redactor#54]
Using Redactor version 10.2.3 along with Browserify and Gulp to include my front-end assets.

The error is coming from like 65, but goes away if you set
 ```
element.redactor('code.set', ngModel.$viewValue || '');
```
to 
 ```
element.redactor('set', ngModel.$viewValue || '');
```

However, this then causes a new "Error: No such method "placeholder.toggle" for Redactor" error.

**Comment by carradjm** [comment]
Something about Browserify and Gulp was causing my app to use an old version of Redactor - once it loaded the new version the error disappeared

**Comment by arevutsky** [comment]
I have same issue. I'm using Redactor version 10.2.4 and latest angular-redactor.

**Comment by aguerre** [comment]
@arevutsky you have to take the angular-redactor-9.x.js ;)
