### ISSUE TITLE
ngModel's value is not updating in html mode in Redactor II

### ISSUE THREAD

**Issue by cusalvi** [TylerGarlick/angular-redactor#72]
I'm experiencing an issue with Redactor II and angular-redactor directive.

While using Source plugin (HTML mode), the ngModel value is not getting updated. It works fine with normal editor mode.

I've hosted the example at - http://redactor-2-demo.herokuapp.com

Here is the recording of the bug - http://recordit.co/9Tfc2AMBZ8

Note: It was working fine with Redactor I and angular-redactor plugin.

Is this a known bug or any setting required to make it work? Thanks.

**Comment by iRet** [comment]
@cusalvi try updating source plugin. The issue seems fixed in current version.

**Comment by cusalvi** [comment]
Yes, Its worked with updated source plugin.
Thanks @iRet
